[package]
name = "cde_config"
version = "0.1.0"
authors = ["cafehaine <kilian.guillaume@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.130"
toml = "0.5.8"
xdg = "2.3.0"
